apiVersion: v1
kind: Pod
metadata:
  name: go-sampleapp
spec:
  containers:
  - name: go-sampleapp
    image: 172.16.194.68/demo-ns/go-sampleapp:0ae09f6ab8c2d47bdf800625a12be3211a4e8f96
  imagePullSecrets:
  - name: registry-secret
