apiVersion: batch/v1
kind: Job
metadata:
  name: go-sampleapp
spec:
  template:
    spec:
      containers:
      - name: go-sampleapp
        image: 172.16.194.68/demo-ns:1add0ddb85469b7891316bcb744ef76effdbe479
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret